apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helm.fullname" . }}-deployment
  labels:
    app: {{ template "helm.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "helm.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ template "helm.fullname" . }}-frontend
    spec:
      containers:
      - name: frontend
        image: docker.pkg.github.com/611-ci-project/cccatalog-frontend/cccatalog:{{ .Values.version }}
        ports:
        - containerPort: 8443
      imagePullSecrets:
        - name: registrycred

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm.fullname" . }}-service
spec:
  type: LoadBalancer
  selector:
    app: {{ template "helm.fullname" . }}-frontend
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443