
#   CCcatalog Frontend
#   Kubernetes Service

apiVersion: v1
kind: Service
metadata:
  name: cc-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: cc-frontend
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
