
#   CCcatalog Frontend
#   Kubernetes Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-frontend-deployment
  labels:
    app: cc-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc-frontend
  template:
    metadata:
      labels:
        app: cc-frontend
    spec:
      containers:
      - name: cc-frontend
        image: 
        command: ["npm"]
        args: ["start"]
        ports:
        - containerPort: 8443
