
#   CCcatalog Frontend
#   Kubernetes Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-frontend-deployment
  labels:
    app: cc-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc-frontend
  template:
    metadata:
      labels:
        app: cc-frontend
    spec:
      containers:
      - name: cc-frontend
        image: docker.pkg.github.com/611-ci-project/cccatalog-frontend/cccatalog:9d291b001f1efce6b7292f407aa88247f7c4628d
        command: ["npm"]
        args: ["start"]
        ports:
        - containerPort: 8443
