on: [push]

jobs:
  lint:
    name: Check source code linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run lint
  unit:
    name: Run unit testing
    runs-on: ubuntu-latest
    steps: 
      - run: echo 'Unit testing is not yet implemented'
  coverage:
    name: Check code coverage of unit test
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Code coverage check is not yet implemented'
  build:
    name: Build source code
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Building source code is not yet implemented'