on: [push]

jobs:
  lint:
    name: Check source code linting
    runs-on: ubuntu-latest
    steps:
      # Checkout code from source repository
      - name: Checkout repository code
        uses: actions/checkout@v1
      # Setup Node in the virtual machine
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      # Install dependencies and run linting
      - name: Install npm dependencies
        run: npm install
      - name: Run source code linting
        run: npm run lint
  unit:
    name: Run unit testing
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository code
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install npm dependencies
        run: npm install
      - name: Run unit testing 
        run: npm test
      # TODO: - name: Upload test report artifact
  coverage:
    name: Check code coverage of unit test
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Code coverage check is not yet implemented'
  build:
    name: Build source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install npm dependencies
        run: npm install
      - name: Build application for production
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist