name: Release from feature branch
on:
  issue_comment:
    types: [created, edited]
    branches:
      - 'feature/*'
jobs:
  helm:
    name: Package Helm chart
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/release')
    steps: 
    - name: Checkout repository code
      uses: actions/checkout@v1
    - name: Set release version and image tag 
      run: |
        version=$(echo "${{ github.event.comment.body }}" | awk '{print $2}')
        echo ::set-env name=VERSION::$version
        tag=$(echo "${{ github.event.comment.body }}" | awk '{print $4}')
        echo ::set-env name=TAG::$tag
    - name: Updating Helm
      run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - name: Packaging Helm chart
      run: |
        helm package helm --set version=${{ env.VERSION }} --app-version=0.1.0
    - name: Uploading Helm chart
      uses: actions/upload-artifact@v1
      with:
        name: helm-0.1.0.tgz
        path: helm-0.1.0.tgz
    - name: Export Kubeconfig
      run: echo ::set-env name=KUBECONFIG::${{ secrets.KUBE_CONF }}
    - name: Installing Helm chart
      run: helm install helm-0.1.0.tgz --generate-name