on: [push]

jobs:
#  docker_build_job:
#    runs-on: ubuntu-latest
#    name: Build and publish Docker image
#    steps:
#    # Checkout code from repository to virtual machine
#    - name: Checkout
#      uses: actions/checkout@v1
#    # Login to GitHub's Docker image repository
#    - name: Docker login
#      uses: azure/docker-login@v1
#      with:
#        login-server: docker.pkg.github.com
#        username: ${{ secrets.GITHUB_USERNAME }}
#        password: ${{ secrets.GITHUB_ACCESS_TOKEN }}
#    # Build & push Docker image 
#    - run: |
#        docker build . -t docker.pkg.github.com/611-ci-project/cccatalog-frontend/cccatalog:${{ github.sha }}
#        docker push docker.pkg.github.com/611-ci-project/cccatalog-frontend/cccatalog:${{ github.sha }}
  setup_kubernetes_job:
      runs-on: ubuntu-latest
      name: Deploy to kubernetes
      steps:
      - name: install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest' # default is latest stable
        id: install
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Decrypt conf file
        run: ./scripts/decrypt.sh
        env:
          DECRYPT_CONF: ${{ secrets.DECRYPT_CONF }}
      - name: set context
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: $HOME/secrets/admin.conf # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
        id: setcontext
      - name: Echo kubeconfig
        run: cat $KUBECONFIG
      - name: Deploy to kubernetes
        uses: Azure/k8s-deploy@v1
        with:
         manifests: |
          kubernetes/cc-frontend-deployment.yml
          kubernetes/cc-frontend-service.yml
         images: 'docker.pkg.github.com/611-ci-project/cccatalog-frontend/cccatalog:b19ecff94e8b1e30d885feb81a9ac4df28f4ca97'
         imagepullsecrets: |
           regcred
         kubectl-version: 'latest'
