
#   Production pipeline
#   611-CI-project/cccatalog-frontend

name: Production
on:
  pull_request:
    branches:
      - master

jobs:
  - name: Deploy production image to production environment #special tagging, latest release?
    run: echo 'Not yet implemented'