
#   Development pipeline
#   611-CI-project/cccatalog-frontend

name: pull request 
on:
  pull_request:
    branches:
      - master

jobs:
  publish_image:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
    # Checkout code from repository to virtual machine
    - name: Checkout
      uses: actions/checkout@v1
    # Login to GitHub's Docker image repository
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ secrets.GITHUB_USERNAME }}
        password: ${{ secrets.GITHUB_ACCESS_TOKEN }}
    # Build & push Docker image 
    - run: |
        docker build . -t docker.pkg.github.com/611-ci-project/cccatalog-frontend/cccatalog:${{ github.sha }}
        docker push docker.pkg.github.com/611-ci-project/cccatalog-frontend/cccatalog:${{ github.sha }}

  kubernetes:
      needs: [publish_image]
      runs-on: ubuntu-latest
      name: Deploy to staging kubernetes cluster
      steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Set context to staging cluster
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{secrets.KUBE_CONF}}
        id: setcontext
      - name: Deploy to staging cluster
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            kubernetes/cc-frontend-deployment.yml
            kubernetes/cc-frontend-service.yml
          images: 'docker.pkg.github.com/611-ci-project/cccatalog-frontend/cccatalog:${{ github.sha}}'
          imagepullsecrets: regcred
