

#   Release pipeline
#   611-CI-project/cccatalog-frontend

name: Release from feature branch
on:
  issue_comment:
    types: [created, edited]
    branches:
      - 'feature/*'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/release')
    name: check if triggered
    steps: 
    - name: Set release value
      run: echo ::set-env name=action_state::yellow
    - name: print variable value
      run: echo $action_state



