

#   Release pipeline
#   611-CI-project/cccatalog-frontend

name: Release from feature branch
on:
  pull_request:
    branches:
      - 'feature/*'

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Find right image
    steps:
    - name: Check if image is in the release asset list #special tagging, latest release?
      run: echo 'Not yet implemented'