

#   Release pipeline
#   611-CI-project/cccatalog-frontend

name: Release from feature branch
on:
  issue_comment:
    types: [created, edited]
    branches:
      - 'feature/*'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/release')
    name: Get values for version and tag
    steps: 
    - name: Set release version and image tag 
      run: |
        version=$(echo "${{ github.event.comment.body }}" | awk '{print $2}')
        echo ::set-env name=VERSION::$version
        tag=$(echo "${{ github.event.comment.body }}" | awk '{print $4}')
        echo ::set-env name=TAG::$tag
    - name: Login to Docker
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ secrets.GITHUB_USERNAME }}
        password: ${{ secrets.GITHUB_ACCESS_TOKEN }}
    - name: Pull image from registry
      run: docker tag docker.pkg.github.com/611-ci-project/cccatalog-frontend/cccatalog:${{env.TAG}} docker.pkg.github.com/611-ci-project/cccatalog-frontend/cccatalog:${{env.VERSION}}



