

#   Release pipeline
#   611-CI-project/cccatalog-frontend

name: Release from feature branch
on:
  issue_comment:
    types: [created, edited]
    branches:
      - 'feature/*'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/release')
    name: Get values for version and tag
    steps: 
    - name: Set release version and image tag 
      run: |
        version=$(echo "${{ github.event.comment.body }}" | awk '{print $2}')
        echo ::set-env name=VERSION:: $version
        tag=$(echo "${{ github.event.comment.body }}" | awk '{print $4}')
        echo ::set-env name=TAG:: $tag
    - name: print VERSION value
      run: echo $VERSION
    - name: print TAG value
      run: echo $TAG



