

#   Release pipeline
#   611-CI-project/cccatalog-frontend

name: Release from feature branch
on:
  issue_comment:
    types: [created, edited]
    branches:
      - 'feature/*'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/release')
    name: check if triggered
    steps: 
    - name: Set version value and image tag
      run: echo "${{github.event.comment.body}}"
      env:
        VERSION: $(echo "${{github.event.comment.body}}" | awk '{print $2}')
    - name: Check variable
      run: echo $VERSION


