

#   Release pipeline
#   611-CI-project/cccatalog-frontend

name: Release from feature branch
on:
  issue_comment:
    types: [created, edited]
    branches:
      - 'feature/*'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/release')
    name: check if triggered
    steps: 
    - name: Dump github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
