name: Rollback production release
on:
  issue_comment:
    types: [created, edited]
    branches:
      - 'feature/*'
jobs:
  helm:
    name: Rollback helm release
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/rollback')
    steps: 
    - name: Set revision number
      run: |
        version=$(echo "${{ github.event.comment.body }}" | awk '{print $2}')
        echo ::set-env name=REVISION::$REVISION
    - name: Updating Helm to latest 3.x
      run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - name: Setting cluster context to production cluster
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{secrets.KUBE_CONF2}}
    - name: Rolling back helm chart to specified revision
      run: helm rollback helm ${{ env.REVISION }}